# Generated by Django 5.2.16 on 2026-07-29 09:02

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("education", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "currency",
                    models.CharField(
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Currency must be a three-letter uppercase ISO 4217 code.",
                                regex="^[A-Z]{3}$",
                            )
                        ],
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("tuition", "Tuition"), ("materials", "Materials")],
                        default="tuition",
                        max_length=20,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="education.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "id"],
                "indexes": [
                    models.Index(fields=["student", "date"], name="payment_student_date_idx")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gte", 0)), name="payment_amount_non_negative"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("currency__regex", "^[A-Z]{3}$")),
                        name="payment_currency_three_uppercase_letters",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("kind__in", ("tuition", "materials"))),
                        name="payment_kind_valid",
                    ),
                ],
            },
        ),
    ]
