# Generated by Django 5.2.16 on 2026-07-29 09:02

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("education", "0001_initial"),
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="ScheduleEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("day_of_week", models.PositiveSmallIntegerField()),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_entries",
                        to="education.group",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_entries",
                        to="curriculum.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["group", "day_of_week", "start_time", "id"],
            },
        ),
        migrations.CreateModel(
            name="GroupSubject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_assignments",
                        to="education.group",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_assignments",
                        to="curriculum.subject",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="curriculum.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["subject", "name", "id"],
            },
        ),
        migrations.CreateModel(
            name="TopicCriterion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("max_points", models.PositiveIntegerField()),
                ("position", models.PositiveSmallIntegerField(default=0)),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criteria",
                        to="curriculum.topic",
                    ),
                ),
            ],
            options={
                "ordering": ["topic", "position", "id"],
            },
        ),
        migrations.CreateModel(
            name="TopicGroupAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic_assignments",
                        to="education.group",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_assignments",
                        to="curriculum.topic",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TopicPeriodAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic_assignments",
                        to="education.academicperiod",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="period_assignments",
                        to="curriculum.topic",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(
                fields=["school", "is_active", "name"], name="subject_school_active_name_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="subject",
            constraint=models.UniqueConstraint(
                fields=("school", "name"), name="subject_unique_name_per_school"
            ),
        ),
        migrations.AddIndex(
            model_name="scheduleentry",
            index=models.Index(
                fields=["group", "day_of_week"], name="schedule_entry_group_day_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduleentry",
            constraint=models.UniqueConstraint(
                fields=("group", "subject", "day_of_week", "start_time"),
                name="schedule_entry_unique_slot",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduleentry",
            constraint=models.CheckConstraint(
                condition=models.Q(("day_of_week__gte", 1), ("day_of_week__lte", 7)),
                name="schedule_entry_day_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduleentry",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("end_time__isnull", True),
                    models.Q(
                        ("start_time__isnull", False), ("end_time__gt", models.F("start_time"))
                    ),
                    _connector="OR",
                ),
                name="schedule_entry_times_ordered",
            ),
        ),
        migrations.AddConstraint(
            model_name="groupsubject",
            constraint=models.UniqueConstraint(
                fields=("group", "subject"), name="group_subject_unique_pair"
            ),
        ),
        migrations.AddIndex(
            model_name="topic",
            index=models.Index(
                fields=["subject", "is_active", "name"], name="topic_subject_active_name_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="topic",
            constraint=models.UniqueConstraint(
                fields=("subject", "name"), name="topic_unique_name_per_subject"
            ),
        ),
        migrations.AddConstraint(
            model_name="topiccriterion",
            constraint=models.UniqueConstraint(
                fields=("topic", "name"), name="topic_criterion_unique_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="topiccriterion",
            constraint=models.UniqueConstraint(
                fields=("topic", "position"), name="topic_criterion_unique_position"
            ),
        ),
        migrations.AddConstraint(
            model_name="topiccriterion",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_points__gt", 0)),
                name="topic_criterion_max_points_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="topicgroupassignment",
            constraint=models.UniqueConstraint(
                fields=("topic", "group"), name="topic_group_assignment_unique_pair"
            ),
        ),
        migrations.AddConstraint(
            model_name="topicperiodassignment",
            constraint=models.UniqueConstraint(
                fields=("topic", "academic_period"), name="topic_period_assignment_unique_pair"
            ),
        ),
    ]
