# Generated by Django 5.2.16 on 2026-07-29 10:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
        ('education', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('teacher', 'Teacher')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='schools.school')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='school_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['school', 'role', 'user', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TeachingAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='education.group')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='schools.membership')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='curriculum.subject')),
            ],
            options={
                'ordering': ['membership', 'group', 'subject', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['school', 'role', 'is_active'], name='membership_school_role_idx'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['user', 'is_active'], name='membership_user_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user', 'school'), name='school_membership_unique_user_school'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ('admin', 'teacher'))), name='school_membership_role_valid'),
        ),
        migrations.AddIndex(
            model_name='teachingassignment',
            index=models.Index(fields=['membership', 'group'], name='teaching_member_group_idx'),
        ),
        migrations.AddIndex(
            model_name='teachingassignment',
            index=models.Index(fields=['group', 'subject'], name='teaching_group_subject_idx'),
        ),
        migrations.AddConstraint(
            model_name='teachingassignment',
            constraint=models.UniqueConstraint(fields=('membership', 'group', 'subject'), name='teaching_assignment_unique_scope', nulls_distinct=False),
        ),
    ]
