# Generated by Django 5.2.16 on 2026-07-29 09:02

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("schools", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("action", models.CharField(max_length=150)),
                ("object_type", models.CharField(blank=True, max_length=100)),
                ("object_id", models.UUIDField(blank=True, null=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_events",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["school", "occurred_at"], name="audit_event_school_time_idx"
                    ),
                    models.Index(fields=["school", "action"], name="audit_event_school_action_idx"),
                ],
            },
        ),
    ]
