# Generated by Django 5.2.16 on 2026-07-29 09:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyAuditEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_local_id', models.PositiveBigIntegerField()),
                ('occurred_at', models.DateTimeField()),
                ('action', models.CharField(max_length=150)),
                ('details', models.TextField()),
                ('revert_data', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['occurred_at', 'legacy_local_id', 'id'],
            },
        ),
    ]
