# Generated by Django 5.2.16 on 2026-07-29 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_legacyauditentry'),
        ('imports', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legacyauditentry',
            name='import_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_audit_entries', to='imports.importbatch'),
        ),
        migrations.AddField(
            model_name='legacyauditentry',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_audit_entries', to='schools.school'),
        ),
        migrations.AddIndex(
            model_name='legacyauditentry',
            index=models.Index(fields=['school', 'occurred_at'], name='legacy_audit_school_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='legacyauditentry',
            constraint=models.UniqueConstraint(fields=('import_batch', 'legacy_local_id'), name='legacy_audit_entry_unique_source'),
        ),
    ]
