# Generated by Django 5.2.16 on 2026-07-29 09:02

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=False)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="academic_years",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_active", "name", "id"],
            },
        ),
        migrations.CreateModel(
            name="AcademicPeriod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("quarter", "Quarter"),
                            ("semester", "Semester"),
                            ("year", "Year"),
                            ("custom", "Custom"),
                        ],
                        default="quarter",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("position", models.PositiveSmallIntegerField(default=0)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periods",
                        to="education.academicyear",
                    ),
                ),
            ],
            options={
                "ordering": ["academic_year", "start_date", "position", "id"],
            },
        ),
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("notes", models.TextField(blank=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="education.academicyear",
                    ),
                ),
            ],
            options={
                "ordering": ["academic_year", "name", "id"],
            },
        ),
        migrations.CreateModel(
            name="CalendarException",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("holiday", "Holiday"),
                            ("cancellation", "Cancellation"),
                            ("other", "Other"),
                        ],
                        default="holiday",
                        max_length=20,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=255)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_exceptions",
                        to="education.academicyear",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_exceptions",
                        to="education.group",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "group", "id"],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_name", models.CharField(max_length=150)),
                ("first_name", models.CharField(max_length=150)),
                ("birthday", models.DateField(blank=True, null=True)),
                ("contract_number", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("archived", "Archived"),
                            ("deleted", "Deleted"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("archive_date", models.DateField(blank=True, null=True)),
                ("archive_reason", models.TextField(blank=True)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "ordering": ["last_name", "first_name", "id"],
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_on", models.DateField()),
                ("ended_on", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("transferred", "Transferred"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="education.group",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="education.student",
                    ),
                ),
            ],
            options={
                "ordering": ["student", "-started_on", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="academicyear",
            index=models.Index(fields=["school", "is_active"], name="acyear_school_active_idx"),
        ),
        migrations.AddConstraint(
            model_name="academicyear",
            constraint=models.UniqueConstraint(
                fields=("school", "name"), name="academic_year_unique_name_per_school"
            ),
        ),
        migrations.AddConstraint(
            model_name="academicyear",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("school",),
                name="academic_year_one_active_per_school",
            ),
        ),
        migrations.AddIndex(
            model_name="academicperiod",
            index=models.Index(
                fields=["academic_year", "start_date", "end_date"],
                name="academic_period_year_dates_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="academicperiod",
            constraint=models.UniqueConstraint(
                fields=("academic_year", "name"), name="academic_period_unique_name_per_year"
            ),
        ),
        migrations.AddConstraint(
            model_name="academicperiod",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gte", models.F("start_date"))),
                name="academic_period_dates_ordered",
            ),
        ),
        migrations.AddConstraint(
            model_name="academicperiod",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ("quarter", "semester", "year", "custom"))),
                name="academic_period_kind_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="group",
            index=models.Index(
                fields=["academic_year", "name"], name="education_group_year_name_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="group",
            constraint=models.UniqueConstraint(
                fields=("academic_year", "name"), name="education_group_unique_name_per_year"
            ),
        ),
        migrations.AddIndex(
            model_name="calendarexception",
            index=models.Index(fields=["academic_year", "date"], name="calex_year_date_idx"),
        ),
        migrations.AddIndex(
            model_name="calendarexception",
            index=models.Index(fields=["group", "date"], name="calex_group_date_idx"),
        ),
        migrations.AddConstraint(
            model_name="calendarexception",
            constraint=models.UniqueConstraint(
                condition=models.Q(("group__isnull", True)),
                fields=("academic_year", "date", "kind"),
                name="calendar_exception_unique_school_scope",
            ),
        ),
        migrations.AddConstraint(
            model_name="calendarexception",
            constraint=models.UniqueConstraint(
                condition=models.Q(("group__isnull", False)),
                fields=("academic_year", "group", "date", "kind"),
                name="calendar_exception_unique_group_scope",
            ),
        ),
        migrations.AddConstraint(
            model_name="calendarexception",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ("holiday", "cancellation", "other"))),
                name="calendar_exception_kind_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["school", "status", "last_name"], name="student_school_status_name_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="student",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ("active", "archived", "deleted"))),
                name="student_status_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(fields=["group", "ended_on"], name="enrollment_group_current_idx"),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["student", "started_on"], name="enrollment_student_start_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("ended_on__isnull", True)),
                fields=("student",),
                name="enrollment_one_current_per_student",
            ),
        ),
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ended_on__isnull", True),
                    ("ended_on__gte", models.F("started_on")),
                    _connector="OR",
                ),
                name="enrollment_dates_ordered",
            ),
        ),
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ("active", "completed", "transferred", "archived"))
                ),
                name="enrollment_status_valid",
            ),
        ),
    ]
