# Generated by Django 5.2.16 on 2026-07-29 09:02

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("curriculum", "0001_initial"),
        ("education", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("custom_topic_name", models.CharField(blank=True, max_length=255)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="education.group",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="curriculum.subject",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "start_time", "id"],
            },
        ),
        migrations.CreateModel(
            name="LessonTopic",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveSmallIntegerField(default=0)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic_links",
                        to="journal.lesson",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_links",
                        to="curriculum.topic",
                    ),
                ),
            ],
            options={
                "ordering": ["lesson", "position", "id"],
            },
        ),
        migrations.CreateModel(
            name="StudentLessonState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("grade", models.SmallIntegerField(blank=True, null=True)),
                ("is_present", models.BooleanField(default=True)),
                ("is_excused_absence", models.BooleanField(default=False)),
                ("homework_points", models.SmallIntegerField(blank=True, null=True)),
                ("comment", models.TextField(blank=True)),
                ("note", models.TextField(blank=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_states",
                        to="journal.lesson",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_states",
                        to="education.student",
                    ),
                ),
            ],
            options={
                "ordering": ["lesson", "student", "id"],
            },
        ),
        migrations.CreateModel(
            name="StudentTopicProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("stage", models.PositiveSmallIntegerField(default=0)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic_progress",
                        to="education.student",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_progress",
                        to="curriculum.topic",
                    ),
                ),
            ],
            options={
                "ordering": ["topic", "student", "id"],
            },
        ),
        migrations.CreateModel(
            name="CriterionScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("score", models.PositiveIntegerField()),
                (
                    "criterion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_scores",
                        to="curriculum.topiccriterion",
                    ),
                ),
                (
                    "progress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criterion_scores",
                        to="journal.studenttopicprogress",
                    ),
                ),
            ],
            options={
                "ordering": ["progress", "criterion__position", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(fields=["group", "date"], name="lesson_group_date_idx"),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(fields=["subject", "date"], name="lesson_subject_date_idx"),
        ),
        migrations.AddConstraint(
            model_name="lesson",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("end_time__isnull", True),
                    models.Q(
                        ("start_time__isnull", False), ("end_time__gt", models.F("start_time"))
                    ),
                    _connector="OR",
                ),
                name="lesson_times_ordered",
            ),
        ),
        migrations.AddConstraint(
            model_name="lessontopic",
            constraint=models.UniqueConstraint(
                fields=("lesson", "topic"), name="lesson_topic_unique_pair"
            ),
        ),
        migrations.AddConstraint(
            model_name="lessontopic",
            constraint=models.UniqueConstraint(
                fields=("lesson", "position"), name="lesson_topic_unique_position"
            ),
        ),
        migrations.AddIndex(
            model_name="studentlessonstate",
            index=models.Index(fields=["student", "lesson"], name="st_lesson_lookup_idx"),
        ),
        migrations.AddConstraint(
            model_name="studentlessonstate",
            constraint=models.UniqueConstraint(
                fields=("student", "lesson"), name="student_lesson_state_unique_pair"
            ),
        ),
        migrations.AddConstraint(
            model_name="studentlessonstate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("grade__isnull", True),
                    models.Q(("grade__gte", 0), ("grade__lte", 5)),
                    _connector="OR",
                ),
                name="student_lesson_grade_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentlessonstate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("homework_points__isnull", True),
                    models.Q(("homework_points__gte", 0), ("homework_points__lte", 101)),
                    _connector="OR",
                ),
                name="student_lesson_homework_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentlessonstate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_present", False), ("is_excused_absence", False), _connector="OR"
                ),
                name="student_lesson_attendance_consistent",
            ),
        ),
        migrations.AddIndex(
            model_name="studenttopicprogress",
            index=models.Index(fields=["student", "topic"], name="st_topic_lookup_idx"),
        ),
        migrations.AddConstraint(
            model_name="studenttopicprogress",
            constraint=models.UniqueConstraint(
                fields=("student", "topic"), name="student_topic_progress_unique_pair"
            ),
        ),
        migrations.AddConstraint(
            model_name="studenttopicprogress",
            constraint=models.CheckConstraint(
                condition=models.Q(("stage__gte", 0), ("stage__lte", 100)),
                name="student_topic_progress_stage_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="criterionscore",
            constraint=models.UniqueConstraint(
                fields=("progress", "criterion"), name="criterion_score_unique_pair"
            ),
        ),
        migrations.AddConstraint(
            model_name="criterionscore",
            constraint=models.CheckConstraint(
                condition=models.Q(("score__gte", 0)), name="criterion_score_non_negative"
            ),
        ),
    ]
