# Generated by Django 5.2.16 on 2026-07-29 09:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('export_id', models.CharField(max_length=255, unique=True)),
                ('checksum', models.CharField(max_length=64)),
                ('format', models.CharField(max_length=100)),
                ('format_version', models.PositiveIntegerField()),
                ('source', models.JSONField(default=dict)),
                ('exported_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('counts', models.JSONField(default=dict)),
                ('report', models.JSONField(default=dict)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='schools.school')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LegacyObjectMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(max_length=64)),
                ('legacy_local_id', models.PositiveBigIntegerField()),
                ('server_model', models.CharField(max_length=100)),
                ('server_object_id', models.UUIDField()),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_maps', to='imports.importbatch')),
            ],
            options={
                'ordering': ['entity_type', 'legacy_local_id', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['school', 'status', 'created_at'], name='import_school_status_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('pending', 'running', 'succeeded', 'failed'))), name='import_batch_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.CheckConstraint(condition=models.Q(('format_version__gt', 0)), name='import_batch_format_version_positive'),
        ),
        migrations.AddIndex(
            model_name='legacyobjectmap',
            index=models.Index(fields=['import_batch', 'entity_type', 'legacy_local_id'], name='legacy_object_source_idx'),
        ),
        migrations.AddIndex(
            model_name='legacyobjectmap',
            index=models.Index(fields=['server_model', 'server_object_id'], name='legacy_object_target_idx'),
        ),
        migrations.AddConstraint(
            model_name='legacyobjectmap',
            constraint=models.UniqueConstraint(fields=('import_batch', 'entity_type', 'legacy_local_id'), name='legacy_object_map_unique_source'),
        ),
        migrations.AddConstraint(
            model_name='legacyobjectmap',
            constraint=models.CheckConstraint(condition=models.Q(('legacy_local_id__gt', 0)), name='legacy_object_map_id_positive'),
        ),
    ]
